name: Dependabot
on:
  - pull_request_target

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]'

    env:
      YARN_ENABLE_SCRIPTS: false
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          # Using a Personal Access Token here is required to trigger workflows on our new commit.
          # The default GitHub token doesn't trigger any workflows.
          # See: https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854/2
          token: ${{ secrets.DEPENDABOT_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - run: git lfs pull --include .yarn/

      - name: Setup node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - name: Restore cache
        uses: actions/cache@v4.0.0
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: git checkout HEAD~1 yarn.lock

      - run: yarn install --mode=skip-build

      - name: Commit yarn.lock
        run: |
          cat > private.key << EOF
          "${{ secrets.DEPENDABOT_PGP_SECRET }}"
          EOF
          gpg --import private.key
          git config user.name "Levalicious"
          git config user.email "levknoblock@gmail.com"
          git config user.signingKey "${{ secrets.DEPENDABOT_PGP_PUBKEY }}"
          git config commit.gpgSign true
          git add yarn.lock
          git commit --allow-empty -m '[dependabot] Fix yarn.lock'
          git push